version: "3.8"
networks:
  dev:

services:
  console:
    container_name: movie
    build: ./docker/php_container
    ports:
      - "8080:80"
    volumes:
      - ./docker/php_container/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev